scrape_configs:

  - job_name: 'echo-hello'
    scrape_interval: 1s
    static_configs:
      - targets: ['echo-hello:8080']

  - job_name: 'gin-hello'
    scrape_interval: 1s
    static_configs:
      - targets: [ 'gin-hello:8080' ]