name: Audit

on:
  push:
    branches:
    - 'lab_02*'
  pull_request:
    branches:
    - 'lab_02*'

jobs:

  audit:
    runs-on: ubuntu-20.04
    defaults:
      run:
        working-directory: ./src/
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.22.2


  
    - name: Verify dependencies
      run: go mod verify

    - name: Build
      run: go build -v ./...
    - name: Install mockgen
      run: go install github.com/golang/mock/mockgen@latest
    - name: Build Mocks
      run: make -C ./internal
    - name: Run go vet
      continue-on-error: true
      run: go vet ./...

    - name: Install staticcheck
      run: go install honnef.co/go/tools/cmd/staticcheck@latest

    - name: Run staticcheck
      continue-on-error: true
      run: staticcheck ./...

    - name: Install golint
      run: go install golang.org/x/lint/golint@latest

    - name: Run golint
      continue-on-error: true
      run: golint ./...
    - name: Run tests
      run: go test -race -vet=off ./internal/tests/...
    - name: Install allure
      run: |
          sudo apt-get update
          sudo apt-get install default-jre
          wget https://github.com/allure-framework/allure2/releases/download/2.18.1/allure_2.18.1-1_all.deb
          sudo dpkg -i allure_2.18.1-1_all.deb
    - name: Create  report
      run: make report -C ./internal/tests/